import 'package:get/get.dart';

class LocalString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          "hello": "Hello World",
          "title": "Employee Management",
          "welcome": "Welcome",
          "sub": "Subscribe Now",
          "changelang": "Change Language",
          "login": "Login",
          "emails": "Email",
          "password": "Password",
          "employee_list": "Employee List",
          "no_employee": "No Employee",
          "add_employee": "Add Employee",
          "profile": "Profile",
          "employees": "Employees",
          "edit_employee": "Edit Employee",
          "delete_employee": "Delete Employee",
          "employee_details": "Employee Details",
          "insurance_form": "Health Insurance Form",
          "request_enroll":
              "I request you to enroll me in the health insurance program.",
          "householder_name": "Name of householder",
          "insurance_no": "Insurance No.",
          "relationship_with_householder": "Relationship with householder",
          "homeowner_insurance_no": "Homeowner's Insurance No.",
          "donor_family": "Belonging to the donor family",
          "member_details": "1) Details of the person",
          "person_name_english": "Name in English (BLOCK LETTER)",
          "gender": "Lead: Woman",
          "birth_date": "Date of Birth",
          "month": "Month",
          "year": "Year",
          "province": "Province",
          "education": "Education",
          "first_service_point": "2) First service point",
          "registration_date": "3) Date of Registration",
          "id_card_no": "4) ID Card No. of Target Category",
          "contribution_amount": "5) Contribution amount Rs",
          "approval_statement":
              "6) Approval: All the practices mentioned above are fine.",
          "phone_number": "Phone Mobile No",
          "identity_card_no": "Identity card no",
          "big": "Not big",
          "very_poor": "Very Poor",
          "mdr_tb": "M.D.R. TV",
          "activation_date": "Service Activation Date",
          "leprosy": "Leprosy",
          "hiv_infection": "HIV Infection",
          "ready_to_be_partner": "I am ready to be a partner in punishment",
          "applicant_signature": "7) Signature of applicant guardian",
          "donor_signature": "8) Signature of Donor Associate",
          "government_of_nepal": "Government of Nepal",
          "health_insurance_board": "Health Insurance Board",
          "identity_card_issue_date": "Identity card issue date",
          "contact_number": "Contact No.",
          "toll_free_number": "Toll Free Number",
          "name": "Name",
          "enter_name": "Please enter a name",
          "employee_id": "Employee ID",
          "enter_employee_id": "Please enter employee ID",
          "mobile_number": "Mobile Number",
          "enter_mobile_number": "Please enter a mobile number",
          "valid_mobile_number": "Please enter a valid 10-digit mobile number",
          "email": "Email",
          "enter_email": "Please enter an email",
          "valid_email": "Please enter a valid email address",
          "address_hint": "Address (include province and district)",
          "enter_address": "Please enter an address",
          "address_format":
              "Address province and district separated by a comma",
          "gender": "Gender",
          "male": "Male",
          "female": "Female",
          "other": "Other",
          "level": "Level",
          "status": "Status",
          "active": "Active",
          "terminated": "Terminated",
          "present": "Present",
          "selected": "Selected",
          "select_qualifications": "Select Qualifications Image",
          "selected_profile_pic": "Selected Profile Pic",
          "select_profile_pic": "Select Profile Picture"
        },
        'np_Np': {
          "hello": "नमस्ते दुनिया",
          "title": "कर्मचारी व्यवस्थापन",
          "welcome": "स्वागत छ",
          "sub": "सब्सक्राइब",
          "changelang": "भाषा बदलो",
          "login": "लगइन",
          "emails": "ईमेल",
          "password": "पासवर्ड",
          "employee_list": "कर्मचारी सूची",
          "no_employee": "कर्मचारी छैनन्",
          "add_employee": "कर्मचारी थप्नुहोस्",
          "profile": "प्रोफाइल",
          "employees": "कर्मचारीहरू",
          "edit_employee": "कर्मचारी सम्पादन गर्नुहोस्",
          "delete_employee": "कर्मचारी हटाउनुहोस्",
          "employee_details": "कर्मचारी विवरण",
          "insurance_form": "बीमालेख फाराम",
          "request_enroll":
              "स्वास्थ्य बीमा कार्यक्रममा मलाई आवद्ध गरिदिनु हुन अनुरोध गर्दछु।",
          "householder_name": "घरमूलीको नाम",
          "insurance_no": "बीमा ने.",
          "relationship_with_householder": "घरमूलीसंगको नाता",
          "homeowner_insurance_no": "घरमूलीको बीमा नं",
          "donor_family": "दता भएका परिवारकी",
          "member_details": "१) व्यक्तिको विवरण",
          "person_name_english": "नामयर अंग्रेजीमा (BLOCK LETTER)",
          "gender": "लिड: महिला",
          "birth_date": "जन्म मिति",
          "month": "महिना",
          "year": "सान",
          "province": "प्रदेश",
          "education": "शिक्षा",
          "first_service_point": "२) प्रथम सेवा बिन्दु",
          "registration_date": "३) दर्ता मिति",
          "id_card_no": "४) लक्षित वर्गको परिचयपत्र नं.",
          "contribution_amount": "५) योगदान रकम रु",
          "approval_statement": "६) मञ्जुरी: माधि उल्लेखित सबै व्यहोरा ठीक छ।",
          "phone_number": "फोन मोबाईल नं.",
          "identity_card_no": "परिचय पत्र नम्बर",
          "big": "बड़ा न",
          "very_poor": "अति गरीब",
          "mdr_tb": "एम डि.आर.टिवी",
          "activation_date": "सेवा क्रियाशील हुने मिति",
          "leprosy": "कष्ठरोगी",
          "hiv_infection": "एच आ्ई भी संकमित",
          "ready_to_be_partner": "सजायको भागीदार हुन तयार छु।",
          "applicant_signature": "७) आवेदक संरक्षकको हस्ताक्षर",
          "donor_signature": "८) दता सहयोगीको दस्तखत",
          "government_of_nepal": "नेपाल सरकार",
          "health_insurance_board": "स्वास्थ्य बीमा बोर्ड",
          "identity_card_issue_date": "परिचय पत्र जारी मिति",
          "contact_number": "सम्पर्क नम्बर",
          "toll_free_number": "टोल फ्रि नम्बर",
          "name": "नाम",
          "employee_id": "कर्मचारी आईडी",
          "mobile_number": "मोबाइल नम्बर",
          "email": "इमेल",
          "enter_email":
              "कृपया इमेल प्रविष्ट गर्नुहोस्", // Added the missing entry
          "valid_email": "Please enter a valid email address",
          "address_hint": "ठेगाना (प्रदेश र जिल्ला सहित)",
          "enter_address": "कृपया ठेगाना प्रविष्ट गर्नुहोस्",
          "address_format":
              "ठेगाना प्रदेश र जिल्ला अलपत्र गरेर, एक अल्छि संलग्न गरेर",
          "selected": "Selected",
          "select_qualifications": "योग्यता छवि चयन गर्नुहोस्",
          "selected_profile_pic": "प्रोफाइल चित्र चयन गर्नुहोस्",
          "select_profile_pic": "प्रोफाइल चित्र चयन गर्नुहोस्",
          "save": "सेभ गर्नुहोस्",
        }
      };
}
